services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=intrusion
    volumes:
      - ./dbentry/:/docker-entrypoint-initdb.d:ro
      - ./data/:/tmp/data:rw